# Generated by Django 2.1.3 on 2018-12-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181224_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='code',
            new_name='book_code',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_title',
        ),
    ]
